### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by yfrindel** [rfennell/AzurePipelines#1170]
### Azure DevOps Extensions

WIKI PDF Generator

### Platform

Azure DevOps Services

### Describe the bug

Unexpected error at the end of the process :
![image](https://user-images.githubusercontent.com/22955005/146177178-48f1dca6-3852-470a-90b9-14f25135ff9b.png)

### Repo Steps

execute the build pipeline

**Comment by rfennell** [comment]
This is an issue with the underlying tool. You need to raise the issue in its repo https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport

**Comment by yfrindel** [comment]
Ok, thx

**Comment by yfrindel** [comment]
Could it be possible to specify the version to use for the Wiki PDF exporter? 
![image](https://user-images.githubusercontent.com/22955005/146341373-5aff0d43-4024-48b5-b89e-afa035fc0f28.png)
I would like to use the previous version

**Comment by rfennell** [comment]
No, it is not possible due to [NPM package I use to download the GitHub release](download-github-release). It only allows the latest or the latest prerelease version of the requested package. Whist doing the last update of my task I looked for alternatives but found none, and was not willing to write my own tool as the is a workaround if you require a specific version of the underlying tool.

The workaround is to use download the version of the tool you want to use and place it in a known location that our agents have access to e.g. included as [resource](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema) such as a repo, artifact or maybe a secure file. This can then be referenced with the `overrideExePath` parameter on the task

**Comment by yfrindel** [comment]
I have finally choosen to download the 3.3.1 version with a script : 
![image](https://user-images.githubusercontent.com/22955005/146362317-337de1c7-dd8f-4005-85a5-d599bf444218.png)
