### ISSUE TITLE
XplatReleaseNotes fails when a git repo is an artifact

### ISSUE THREAD

**Issue by gregpakes** [rfennell/AzurePipelines#384]
The Xplat Release Notes fails when you have an artifact which is a git repo.

```
2018-09-27T14:38:22.1769775Z Looking at artifact [_iSAMS.Docker]
2018-09-27T14:38:22.1770077Z Build Number: [c80076f7]
2018-09-27T14:38:22.1770442Z Looking for the [_iSAMS.Docker] in the most recent successful release [iSAMS_18.9.24.8]
2018-09-27T14:38:22.1770741Z Found artifact [_iSAMS.Docker] with build number [01914223] in release [iSAMS_18.9.24.8]
2018-09-27T14:38:22.1770976Z Checking what commits and workitems have changed from [01914223] => [c80076f7]
2018-09-27T14:38:22.1772002Z ##[debug]ReleaseNotes.Fix349=undefined
2018-09-27T14:38:22.2142723Z ##[error]Error: fromBuildId or toBuildId is null. Supply a valid value and try again.
```

**Comment by rfennell** [comment]
When you say a Git repo you mean a non Azure DevOps hosted Git repo, and a non GitHub hosted GitRepo?

**Comment by rfennell** [comment]
Should work with azure devops repo. I wonder if they have changed a name of the repo type?

**Comment by rfennell** [comment]
OK, I have done some testing and I cannot get a repo on this issue.

I am using a [pipeline](https://dev.azure.com/richardfennell/GitHub/_releaseProgress?releaseId=939&_a=release-pipeline-progress&view=overview) that tests both the V1 and V2 extensions . This release:

- Uses a Azure DevOps build on the same instance as its artifact
- Runs the V1 task and emails the results (V1.9.1 manually updated version number, had not expected to touch this again, maybe should removed but that is another question)
- Runs the V2 task and emails the results (V2.62 updated version  number by pipeline)
- The runs another build to add new commits for the next run (you can't do this at the start as the build details are 'locked' as the release starts)

As I noted this is running against an update private 2.6.2 of the extension, with a matching V2 task, but all this does is fix the V1 (now 1.9.1) to handle dev.azure.com URLs (not required for V2) and update a load of NPM packages to get rid of vulnerabilities. So this should not effect your issue.

The  V1 template returns

```
# Release notes
## Notes for release  Validate - Git XplatGenerateReleaseNotes **Release Number**  : Release - 2374 Attempt 1 **Release completed** : 2018-10-03T11:39:17.207Z **Compared Release Number**  : Release - 2373 Attempt 1

### Associated work items
* ** Product Backlog Item 13 ** Assigned by: Richard Fennell (Work MSA) <bm-richard.fennell@outlook.com>  PBI to link
* ** Bug 14 ** Assigned by: undefined  Bug to link

### Associated commits
* **ID 3640a2453cf5f850de52198e4f26494bf53ceaf5 ** Automated Repo Update #13 #14

```

The V2 returns

```
## Notes for release  Validate - Git XplatGenerateReleaseNotes **Release Number**  : Release - 2374 Attempt 1 **Release completed** : Wed Oct 03 2018 11:39:17 GMT+0000 (Coordinated Universal Time) **Compared Release Number**  : Release - 2373 Attempt 1

### Associated work items
* ** Product Backlog Item 13 ** Assigned by: Richard Fennell (Work MSA) <bm-richard.fennell@outlook.com>  PBI to link
* ** Bug 14 ** Assigned by: undefined  Bug to link

### Associated commits
* ** ID 3640a2453cf5f850de52198e4f26494bf53ceaf5 ** Automated Repo Update #13 #14

```

So is working, so how is different to your setup?

**Comment by gregpakes** [comment]
Hi,

I mean an actual git repo. Not a build artifact.  Looking at your pipeline I’m not seeing a git repo as an artifact.

Thanks,

Greg

**Comment by rfennell** [comment]
Ah, sorry misunderstood, I will mod my test pipeline

**Comment by rfennell** [comment]
OK @gregpakes I have done some more testing, and update the private release of the extension to do testing, which you can have access to if you need. 

The behavior of of the Azure DevOps UI is to only return WI/Commits from Pipeline based builds.

On the old V1 task there was a problem that it tried to get build details from non build artifacts, I fixed this. I also added support for the dev.azure.com format

> Side note, I wonder how long to keep V1 in the extension package?

On the V2 task there was no need to fix the URLs the API does that, but I have struggled to get a repo on your issue. But when it occurs the issue is that again if the artifact is not a pipeline build we get a failure, but not all the time - hence the problem

You can see on [my tests](https://dev.azure.com/richardfennell/GitHub/_releases2?definitionId=23&view=mine&_a=releases) only 2379 shows the problem. The two after that should have failed too.

I think a guard 'if' must be needed (as per V1), but the API wrapper library does not give an easy way to see the artifact type (unlike the direct API call in V1). I thought we might be able to use the BuildDefinationID, check if this is numeric, but both Git commits and BuildID as numbers so no luck there.

I suppose the alternative is a try/catch

Can't think why it is not repeatable all the time.

**Comment by rfennell** [comment]
I have now removed V1 from the package so this issue mostly goes away

As I can't get a repo for V2. I am closing this issue. If this issue returns, we we can get a repo, please do not hesitate to re-open it
