### ISSUE TITLE
 Generate Release Notes skipping work items linked from external Git repository commit

### ISSUE THREAD

**Issue by koystinen** [rfennell/AzurePipelines#428]
Background: Azure DevOps Service (VSTS)
Task: Generate Release Notes 
Version: 2.* (latest?)

Issue:
@@WILOOP@@ is ignoring work items linked to the builds from GitHub commit (new VSTS feature, and AB# syntax)
Work items are appear in the release summary, but not in the file generated by plugin

Expected:
Work items linked to release/build to appear in generated file via WILOOP

Steps to reproduce:
1) Using Azure Devops "GitHub connection feature" introduced in December update (Project->Settings->Boards->GitHub Connection)
2) Configure a Azure Pipeline to run a build from GitHub repo.
3) Made a commit, with a comment that would link commit and build to the user story (work item)...
For example: "AB#1243 this is test"
4) Run a build, against the commit created on step 3.
- you'll see that user story will appear in the list of build work items.
Suspected Issue: if build contains task Generate Release Notes, the WILOOP will not have user story 1234 in the output. (have not verified)
5) Run a release pipeline, against build created on step 3.
Actually Issue : if release contains task "Generate Release Notes", then generated file will not include user story 1234, even though release summary shows such work item

Notes:
This issue does not happen on work-items linked to the build via commit from VSTS "Internal" Git repository (we have release notes that generate fine there), seems to be only affecting work-items linked from external git repository using new AB# syntax .

**Comment by rfennell** [comment]
Just to confirm something

Are use using the 
- [PowerShell Generate Release Notes ](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-GenerateReleaseNotes-Task) which works in builds and releases, but uses my own bespoke logic to get the WI/Commits
- or the [Cross Platform Versions](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) which only works in releases and uses Microsoft's APIs to get the lists of WI/Commits

Both versions have code to just ignore and build based in GitHub. This is because in the past there was was to get the required information. As you point out this is potentially no longer true. However it would require some enhancement.

My intention is to try to move towards deprication of the older PowerShell version, so I need to see if the GitHub related data is available via the MS Api.

**Comment by koystinen** [comment]
I am using original *PowerShell Generate Release Notes* in Release... I can try new Cross Platform Version to see if it works any better.

**Comment by rfennell** [comment]
I doubt it will be much better as I have a switch at present that ignores GITHUB hosted builds. I will need tlo make a change (if I can)

**Comment by isahuntercsggit** [comment]
Did you make that change?

**Comment by rfennell** [comment]
I have not had much capacity for OSS work of late, so sorry not looked into this yet

**Comment by rfennell** [comment]
This has been partial addressed in #620 and the work to sort all the GitHub private repo cases is being tracked there
