### ISSUE TITLE
Include a Custom Field value in the list of Associated Work Items

### ISSUE THREAD

**Issue by marwaelghali** [rfennell/AzurePipelines#436]
### Azure DevOps Extension you are using
Generate Release Notes Build Task for Azure DevOps Pipelines v 2.23.1

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
 v 2.23.1

### Expected behaviour and actual behaviour
Would like to include a Custom Field that we've created in our Inherited Organization Process, in the description of the Work Item, but can't figure out the format to be used in the template to refer to the custom field.
How should the ReferenceName of the Custom Field be formatted? Or is this feature not supported?

### Steps to reproduce the problem
Using the below template in the task:

#Release notes for build $defname  

**Build Number**  : $($build.buildnumber)    
**Build started** : $("{0:dd/MM/yyyy HH:mm:ss}" -f [datetime]$build.startTime)     
**Source Branch** : $($build.sourceBranch)  

###Associated work items  
@@WILOOP@@  
$($widetail.fields.'System.WorkItemType') $($widetail.id)
Assigned To: $($widetail.fields.'System.AssignedTo'.'DisplayName')
Title: $($widetail.fields.'System.Title') 
_**Custom Field: $($widetail.fields.'FieldName')**_
Description: $($widetail.fields.'System.Description') 

@@WILOOP@@  

###Associated change sets/commits  
@@CSLOOP@@  
**ID $($csdetail.changesetid)$($csdetail.commitid)
$($csdetail.comment)    

@@CSLOOP@@

**Comment by rfennell** [comment]
Try Custom Field: $($widetail.fields.['FieldName'] )

**Comment by marwaelghali** [comment]
Sorry, doesn't work. 
Using the square brackets issues an error, and without them, no output is produced.

**Comment by rfennell** [comment]
Fields are an array, so that is not far off. I am site at a client so can't check anymore now, but try searching the closed issues, think it might have been asked before

**Comment by marwaelghali** [comment]
Thanks for the quick response.
Browsed through the existing issues, but couldn't find anything that looks related from looking at the titles, or searching by a relevant key.
Hope you get the time to check this out soon.
Thanks again.

**Comment by rfennell** [comment]
OK done a bit of research. As you you had tried the general format will be 

`$($widetail.fields.'System.Title') `

The problem is what is the name for a custom field?

I think the issue is that the custom field name is pre-pended by the custom template name (I am assuming you are using inherited processes, not the old XML based stiff from on prem TFS imported to Azure DevOps)

So you name maybe 

`$($widetail.fields.'MyProcess.MyCustomField') `

Have a look at this set of [docs](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-fields?view=azure-devops) on the background.

Also a trick I have done in the past, as these custom names can be a problem to find, is to create a WI Query in Visual Studio, as this has the option to save as a .WIQL file. This is just text and you can read the field name out of the file. 

Does this help?

**Comment by marwaelghali** [comment]
Thank you so much for getting back.
I tried the WI Query in VS, and turns out the custom field is named 'Custom.FieldName', so that worked out.
Thanks again.
