### ISSUE TITLE
Suggestion: XplatGenerateReleaseNotes to use a different template engine

### ISSUE THREAD

**Issue by areve** [rfennell/AzurePipelines#467]
Regarding **XplatGenerateReleaseNotes** the template capability is inferior to that of GenerateReleaseNotes because in that I could add PowerShell script inside the $( )'s to format dates, find first item in list etc.

Would it be better to Handlebars.js (or similar) for templates instead? This would allow a lot more functionality and there would be less code to maintain in this project. It would however mean existing users would need to change their templates. 

What do you think?

**Comment by rfennell** [comment]
The choice of 'raw' javascript was made due to my lack of experience when I created this CrossPlat version, hence not using any libraries, and to minimise changes in templates from the PS Version

I am however very retisent to change because, as you say it would be a breaking change. If there was such a change I think it would have to be behind a features flag/checkbox

So I think for now this is not something I am going to put effort into at this time. 

Always happy to consider PRs :)
