### ISSUE TITLE
Unable to use the cross platform task

### ISSUE THREAD

**Issue by vlivanov** [rfennell/AzurePipelines#468]
### Azure DevOps Extension you are using
Generate Release Notes(Crossplatform)

### Where are you running it?
VSTS

### Version of Extension/Task
Latest(3.0.8)

### Expected behaviour and actual behaviour
After installing the extension I expect the task to be addable to the build.   

### Steps to reproduce the problem
1. Install the Crossplatform Generate Release Notes Extension
2. Open a Pipeline
3. Press edit
4. Search for crossplatform
5. Expected: the task appears
6. Actual: Only extension is visible, no tasks available

**Comment by rfennell** [comment]
My cross platform release notes generator only works in releases as due to the API calls it makes, the same API calls the Azure DevOps API uses. I would recommend this is where you generate your release notes if possible.

If you really need to create them in a build look at my older [PowerShell based extension](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-GenerateReleaseNotes-Task) this works in builds and release, but only on Windows agent, and used my own logic, not Microsoft's API

However, I am a bit confused as you say cross platform, but the version number you mention is the PowerShell extension, so it may be a different problem.

FYI: I am looking at adding build support to my cross platform version at some point, but not in the near term

**Comment by rfennell** [comment]
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it
