### ISSUE TITLE
VersionDacPac slow on bigger projects

### ISSUE THREAD

**Issue by Arturas-K** [rfennell/AzurePipelines#486]
### Azure DevOps Extension you are using
Manifest Versioning Build Tasks - VersionDacpac

### Where are you running it?
- Azure DevOps Service (VSTS) Cloud

### Version of Extension/Task
Latest public version

### Expected behaviour and actual behaviour
Version should be updated in seconds, now it takes minutes

### Steps to reproduce the problem
If you have SQL Database project with a lot of objects updating dacpac artifact using SqlPackage dll becomes very slow.

In my example if i unpack my dacpac model.sql is 53k lines of t-sql.

Attaching verbose log output for the task:
[VersionDacPacLog.txt](https://github.com/rfennell/AzurePipelines/files/3162307/VersionDacPacLog.txt)

## Suggestion
Consider different approach, we ended up updating .sqlproj file before build step to update/add <DacVersion> xml tag.

**Comment by ChrisLGardner** [comment]
It's been a while since I looked at the code for the task so there might be
some optimizations we can make. I'm not sure why we didn't go the route of
updating the XML originally as we do in other tasks but that might be an
option and would allow placing before or after the build so that we don't
break any existing builds that use it.

**Comment by rfennell** [comment]
@ChrisLGardner  is this a duplicated of #373 - we never got to the bottom of that one

**Comment by ChrisLGardner** [comment]
Fixed in 2.14.x release. It now lets you version before or after the build step.
