### ISSUE TITLE
Question @@BUILDLOOP@@ Am I doing something wrong?

### ISSUE THREAD

**Issue by mspradlin2010** [rfennell/AzurePipelines#584]
### Azure DevOps Extension you are using
Generate Release Notes Build Task

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
-Current

### Expected behaviour and actual behaviour
Expected @@BUILDLOOP@@ to loop through all builds between last successful release and new release in my release pipeline, then output all work items associated to all in between builds.  I'm only getting work items from the latest build using the script below.

### Steps to reproduce the problem
including script

`# Release notes for release $defname
**Release Number**  : $($release.name)
**Release completed** $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$release.modifiedOn)

**Changes since last successful releases to '$stagename'**
**Including releases:**
 $(($releases | select-object -ExpandProperty name) -join ", " )

## Builds
@@BUILDLOOP@@
### $($build.definition.name)
**Build Number**  : $($build.buildnumber)
**Build completed** $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.finishTime)
**Source Branch** $($build.sourceBranch)

#### Associated work items
@@WILOOP@@
* #$($widetail.id)
@@WILOOP@@

#### Associated change sets/commits
@@CSLOOP@@
* **ID $($csdetail.changesetid)$($csdetail.commitid)**
  >$($csdetail.comment)
@@CSLOOP@@

----------

@@BUILDLOOP@@`

**Comment by rfennell** [comment]
Stupid question, you are running the task within a release not a build?

This older task can be run in either, it was originally designed to work only in builds, returning a list of associated work items (same as MS UX). I then added support for running in a release. This uses my own logic to work out what builds have run since the last successful deployment.

I tend to recommend people use my newer [Cross Platform version ](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes) as it does not rely on my home grown logic, but uses the same API calls as the MS UX for releases.

I did add support for builds in this crossplatform task too yesterday, this is so it can be used in YAML releases

Anyway, if you choose not to try the other version can you run your release in diags (set a variable system.debug=true) and send the log so I can see what is happening. It should tell you all the builds it is considering

**Comment by mspradlin2010** [comment]
Correct running as a release task.  I'll give the cross platform version a try, thanks for the fast reply.
[ReleaseLog.txt](https://github.com/rfennell/AzurePipelines/files/3917718/ReleaseLog.txt) attached release log in case you wanted to look into it further :)

**Comment by mspradlin2010** [comment]
Side note builds I would have expected in the release are 53, 54, 55

**Comment by rfennell** [comment]
The problem is to do with ln193 in [GenerateReleaseNotes.ps1](https://github.com/rfennell/AzurePipelines/blob/master/Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1)

`$firstBuild = $lastSuccessfulRelease.artifacts | Where-Object { $_.definitionReference.definition.id -eq $defId}`

This should return the last release that was successful and hence the build ID it was generated from. The idea being the you then have a pair of build numbers, the range to include.

So the problem is earlier in the log I can see

`2019-12-03T16:46:53.2307085Z ##[debug]Discovered [1] releases for processing after checking a total of [1] releases` 

We only have one release so it can get a range of release successful or otherwise (Ln 128 for about 20 lines). 

The behaviour is meant to be 
- if first release list everything
- if there has been a successful release before only go back that far for the range

It is due to this  home grown logic that I recommend using the newer Crossplatform task that uses the official APIs

**Comment by mspradlin2010** [comment]
just wanted to post back and let you know i used the cross platform extension and it worked great!

**Comment by rfennell** [comment]
Great news, glad the extension is of use
