### ISSUE TITLE
StopVM task shares name with StartVM 

### ISSUE THREAD

**Issue by riezebosch** [rfennell/AzurePipelines#601]
StopVM task shares name with StartVM which makes it impossible to use in a YAML pipeline:  https://github.com/rfennell/AzurePipelines/blob/master/Extensions/DevTestLab/StopVM/task.json

**Comment by rfennell** [comment]
Thanks for reporting that, I will get this fixed today.

**Comment by rfennell** [comment]
This has been fixed in 1.14.2
 
I have. I have tested that fixing the name for YAML usage does not affect the UI usage so it does not have to be major release, just a minor.

I have also fixed a problem with the release pipeline in that it did not generate the YAML usage documentation. This can now be seem [here](https://github.com/rfennell/AzurePipelines/wiki/DevTestLabs-YAML)
