### ISSUE TITLE
Assigned by: [object Object]

### ISSUE THREAD

**Issue by itsector-esanti** [rfennell/AzurePipelines#732]
Hello!

I noticed in my last Release Notes using Generate Release Notes (Crossplatform), the **Assigned by** field is not showing the right name.
Now, this field is printing **[object Object]** as value.

Could you help me what is the new field I should have to use?

This is my current template:
```
**Build Number**  :  $(Build.buildnumber)
**Source Branch** :  $(Build.sourceBranch) 

### FEATURES
@@WILOOP:RN-FEATURES@@
${widetail.fields['System.Description']}
@@WILOOP:RN-FEATURES@@

### All Work Items
@@WILOOP@@  
* **${widetail.fields['System.WorkItemType']} ${widetail.id}** ${widetail.fields['System.Title']} - **Assigned by:** ${widetail.fields['System.AssignedTo']}
@@WILOOP@@
```
Thank you for your attention!

**Comment by rfennell** [comment]
That is because that property is not a string but an object. 

The best option for handling issues like this is to swap over to the [newer handlebars based template format (the future for this task, adding a lot of functionality)](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task)

You can find a full [sample templates here](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202/Handlebars), but the relevant part is...

```
{{#forEach this.workItems}}
{{#if isFirst}}### WorkItems {{/if}}
*  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
   - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
   - **Tags** {{lookup this.fields 'System.Tags'}}
   - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
   - **Description** {{{lookup this.fields 'System.Description'}}}
   - **Children**
{{/forEach}}
```
