### ISSUE TITLE
WIKI Updater cannot connect to Azure DevOps Server WIKI Repo

### ISSUE THREAD

**Issue by oschke** [rfennell/AzurePipelines#748]
Hello,

I'm using an on-premise Azure DevOps Server with self-hosted agents. My cloned Wiki-URL is as follows "http://servername/collection/project/_git/wikiname".

The problem is that the task always adds "https://..." but in my case I would need "http://..."

Am I missing something?

**Comment by rfennell** [comment]
As detailed in the [documentation](https://github.com/rfennell/AzurePipelines/wiki/WIKI-Updater-Tasks) you have to be careful with the repo URL. You don't to enter the part before the domain name so in your example for 

`http://servername/collection/project/_git/wikiname`

the repo paremeter is 

`servername/collection/project/_git/wikiname`

This is because the task rebuilds with part of the url before this to include login details for Azure DevOps.

To be fair, I get this question a lot, so it is obviously too confusing, I think I need to do something better with the parameter handling logic.

**Comment by rfennell** [comment]
I have decided to make the change so the repo parameter is used in a more obvious way, and still provide legacy support for the old format.

**Comment by oschke** [comment]
Thanks for the quick response. I added the repo parameter as you mentioned but my problem is the same. That the WikiUpdater needs to connect over an unsecure "http://..." instead of "https://..." but as far as I've seen it in the code, it always uses "https://..."

I think with the new format this problem will be solved?

**Comment by rfennell** [comment]
As I have written it thus far it won't, but I think this is a good time to address this issue. It is rare people hit this problem as any Azure DevOps Services or GitHub connections are on HTTPS, as well as many on premise TFS instances.

I will make the change, but I am a little concerned the underlying [Simple- Git](https://www.npmjs.com/package/simple-git) API (and in the end the command line Git tool it calls) might not be too happy on a unsecured

**Comment by rfennell** [comment]
Just publishing 1.14.4 this will
- Sort out the URl tstripping out http/https as needed
- Use the same protocol http/https as specifed in the repo parameter

Let me know if it works for you @oschke

**Comment by oschke** [comment]
I just tested it. It's perfectly working. 

At this point a big thanks for all your work/effort and your great support!!
