### ISSUE TITLE
Release date of stage

### ISSUE THREAD

**Issue by BennyM** [rfennell/AzurePipelines#794]
I have a release pipeline with several stages (development, staging, production).

When generating release notes and accessing the modified on date it will always be the date the release was published on the first stage:

`**Release completed** : ${releaseDetails.modifiedOn} `

I want release notes for every stage, so with the correct date of the release for each stage. We are currently on 2.53.2 of your library. Would upgrading to version 3 and checking "check stage" give the desired result?

Thanks

**Comment by rfennell** [comment]
Is your release pipeline YAML based? The reason I ask is that the multi stage support in V3 is only for YAML as there was already the  equivalent feature of UI based releases.

The answer to question is that for a YAML pipeline the timeline is not currently exposed to the handlebars template engine. 

It could be added but the problem is that it just a large array of objects. In my test pipeline with 4 stage it contain 97 objects

![image](https://user-images.githubusercontent.com/324718/91447086-2dc3a880-e870-11ea-9e41-e6e61b560abf.png)

So exposing the timeline to the template is easy enough, but I can't see an easy way in handlebars to be able to pull out the relevant object. Hence, the reason to no add it. 

I guess one option would be to add just the timeline details for matched stages, would that be enough, basically what is in the screenshot?

**Comment by BennyM** [comment]
Hi

Thank you for the quick reply, it is not YAML based unfortunately. So I think so should just create a pipeline variable instead then?

For a YAML approach I think your solution would be ok.

**Comment by rfennell** [comment]
In that case there is no point moving from V3 from V2 as there have been no changes to UI based release logic. The good news is that the objects exposed by the ReleaseAPI does have the times you are after.

Looking at the `releaseDetails` object we have

![image](https://user-images.githubusercontent.com/324718/91454365-c4946300-e878-11ea-85ed-9b7ea8231d02.png)

So in a  handlebars template you need something like

```
**Release Date to Stage {{releaseDetails.environments.0.name}}**: {{releaseDetails.environments.0.modifiedOn}}
```
giving
```
**Release Date to Stage Windows**: Thu Aug 27 2020 15:16:52 GMT+0100 (British Summer Time)
```

The .0 is just the index into the environments array.The number should be fixed for your release so you can hard code it in the template. 

To get the environments available, you can dump them all out using

```
{{json releaseDetails.environments}}
```

If you wanted to replace the .0 with a name you would have to write a handlebars extension, but I don't think it is worth the effort as the indexes are fixed unless you edit the release definition.

Hope that helps

**Comment by rfennell** [comment]
If anyone is reading this thread and is using the `checkstage` option in a multi-stage YAML pipeline I have now added a new object available to handlebars templates to expose the details of the stage being used for the check in the current build. This new object is called 'currentStage` and has fields as follows

```
{
"previousAttempts":[],
"id":"92770587-919b-56cd-aeeb-c312cc7b9e23",
"parentId":null,
"type":"Stage",
"name":"Documentation",
"startTime":"2020-08-27T17:00:57.283Z",
"finishTime":"2020-08-27T17:01:30.730Z",
"currentOperation":null,
"percentComplete":null,
"state":2,
"result":0,
"resultCode":null,
"changeId":145,
"lastModified":"0001-01-01T00:01:15.000Z",
"workerName":null,
"order":7,
"details":null,
"errorCount":0,
"warningCount":0,
"url":null,
"log":null,
"task":null,
"attempt":1,
"identifier":"Documentation"
}
```
You find this new feature in version 3.8.3
