### ISSUE TITLE
Error when running parallel updates to the same wiki

### ISSUE THREAD

**Issue by luizfdias** [rfennell/AzurePipelines#808]
**Describe the bug**
It seems the problem reported in #478 still exists. When working with multiple releases at the same time, I get the following message:

Error: To https://.visualstudio.com//_git/.wiki
! [remote rejected] wikiMaster -> wikiMaster (TF401028: The reference 'refs/heads/wikiMaster' has already been updated by another client, so you cannot update it. Please try again.)
error: failed to push some refs to 'https://.visualstudio.com//_git/.wiki'

Error: To https://.visualstudio.com//_git/.wiki
! [remote rejected] wikiMaster -> wikiMaster (TF401028: The reference 'refs/heads/wikiMaster' has already been updated by another client, so you cannot update it. Please try again.)
error: failed to push some refs to 'https://.visualstudio.com//_git/.wiki'

**WIKI Updated Task Version: 1.14.4.**

**To Reproduce**
Run to releases in parallel that will update the same wiki.

**Expected behavior**
Retry should be performed automatically by the task after a new pull in git repository.

**What is the issue see:**
 - Azure DevOps Services

**Comment by rfennell** [comment]
The problem here is the way Git works, you can only push to the remote if you are up to date i.e. pulled any changes made by other users/processes. The task, as it stands, does a pull as the last step prior to doing the push, so I can't see I can do any more to mitigate these parallel race conditions from occurring in the first place.

The only thought I have had is that I could put in a retry loop e.g. try a pull/push cycle say 5 times on the pull error before failing the tasks.

Do you have any other thoughts has to how this could be addressed

**Comment by luizfdias** [comment]
I retry loop should be fine. It might be a good idea to have an small interval between each try (maybe 5 seconds?). I don't see any problem in wait a bit more for the task finish as long as it succeed. 

Right now in our release step we run many other tasks before the wiki updater. If wiki updater fails, we have to run all the release step again. That's why is so important to guarantee that the task will be executed with success.

**Comment by rfennell** [comment]
Ok, a retry look it is then. I will look at it as a soon as I get a chance
