### ISSUE TITLE
Wiki link not working?

### ISSUE THREAD

**Issue by DionRS98** [rfennell/AzurePipelines#845]
Hi, I am trying to use the Release Notes Generator and Wiki Updater together. The Release Notes Generator works fine, however as per the Wiki Updater documentation, there is no option to "clone repo" when I navigate to the wiki I want the md file to be published to, only a "clone wiki" option. It provides what looks to be the correct URL, until I run the pipeline and the task fails with

"##[error]Error: Cloning into 'D:\a\1\s\repo'...
remote: TF401019: The Git repository with name or identifier PartsUnlimited.wiki does not exist or you do not have permissions for the operation you are attempting."

I have allowed all permissions and the wiki definitely exists. It works when I use the URL when I go directly to the repo and "clone repo" but this publishes the md file directly to the repo, not to the Wiki.

Do you have any resolution for this?

Kind regards,
Dion

**Comment by foosfam** [comment]
For the life of me I cannot get this to work.  Like Dion, the notes are generated fine.  But when I try to publish to the wiki I get the following error:
remote: TF401019: The Git repository with name or identifier XXXXXXXX.wiki does not exist or you do not have permissions for the operation you are attempting.
fatal: repository 'https://XXXXXXXX.visualstudio.com/XXXXXXXX/_git/XXXXXXXX.wiki/' not found

The wiki is absolutely there and I've checked everything to get this working.  Can I pay for some support on this?  I really need to get this functioning for the final piece of our SDLC.  Thanks so much Richard!

**Comment by rfennell** [comment]
99% of the time the issue is the permissions, the things to check...

1. That the Clone URL of the WIKI is correct, and yours looks the format I would expect for an Azure DevOps built in WIKI, my one, as generated from the `clone wiki` button, is `https://richardfennell@dev.azure.com/richardfennell/Git-project/_git/Git-project.wiki`. Don't worry about the bit before the @ it is removed by the task

1. For authentication
     - If you are using the OAUTH (the build agent user) access option
        - Set the task's `UseAgentToken` parameter to `true`     
        - Make sure the user `<project name> build service` user is granted commit permission - this is the default user for the build agent.
        - If you [changed the build scope](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops#build-job-authorization-scope) then the user 'Project Collection build service` user should have permissions
        - **IMPORTANT** this one got me recently, a default has changed over repo permissions - Make sure that the `Project Collection > Setting > Pipeline > Setting > Limit job authorization scope to referenced Azure DevOps repositories` is not enabled. If set it can block access to the target repo giving the error you see

    - If you are not using the OAUTH (the build agent user) access option i.e. you pass in some credentials
         - Set the task's `UseAgentToken` parameter to `false`
         - Pass in the name of the Azure DevOps  organisation as the user and a valid PAT for a user with permissions to access the repo as the password
         - **THIS IS A GREAT WAY TO GET GOING IF YOU HAVE PROBLEM WITH OAUTH** You can also test these setting using the git command line and the url in the form 'https://<organame>:<pat>@XXXXXXX.visualstudio.com/XXXXXXXX/_git/XXXXXXXX.wiki'


**So I recommend testing using a PAT as the best way to get going. If this works you have a solution to use while you work out the issue with OAUTH.**

The other points to consider are
- Where is the build agent? Is there a proxy or firewall between it and the Azure DevOps Instance?
- If this is the case try using a Microsoft hosted agent just to see if a local networking issue has caused the problem.

**Comment by foosfam** [comment]
Thanks Richard for the quick reply.  The PAT is working but now I'm seeing issues with the notes generation and the wiki task finding the generated md file.

First problem - or is it... I'm seeing this:
Get the file details associated with the commits
Enriched change 0eba0db14e29904ed23c1a8b580595163cfd5162 of type TfsGit
Cannot enriched as location URL not in dev.azure.com format
Enriched change 6525b4d40403fdf6d278d0a1fc2bedaaca0ebb60 of type TfsGit
Cannot enriched as location URL not in dev.azure.com format
Enriched change cd897d28254be961ec6cbf05c1c52e9c00a473e8 of type TfsGit
Cannot enriched as location URL not in dev.azure.com format

Secondly, what I'm seeing in my Wiki Task:
Checking for files using the filter ${Build.ArtifactStagingDirectory)/*.md
Found 0 files
No commit was performed as no files have been added, deleted or edited
Finishing: WikiFolderUpdaterTask

Which confuses me as the notes generation completed successfully with:
Start of payload data dump
{"workItems":[],"commits":[{"id":"0eba0db14e29904ed23c1a8b580595163cfd5162","message":"Updated ReleaseNotes-PublishToWiki.yml","type":"TfsGit","author":{"displayName":"Matthew Foos","_links":{"avatar":{"href":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk"}},"id":null,"uniqueName":"matthewf@grantcare.com"},"timestamp":"2020-11-03T18:49:30.000Z","location":"https://grantcare.visualstudio.com/_apis/git/repositories/1ab6579f-a5fd-423b-955c-dd56829384bc/commits/0eba0db14e29904ed23c1a8b580595163cfd5162","pusher":"c9a11d9c-9cd4-67b9-af06-f1c4378a5d0d","changes":[]},{"id":"6525b4d40403fdf6d278d0a1fc2bedaaca0ebb60","message":"Updated ReleaseNotes-PublishToWiki.yml","type":"TfsGit","author":{"displayName":"Matthew Foos","_links":{"avatar":{"href":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk"}},"id":null,"uniqueName":"matthewf@grantcare.com"},"timestamp":"2020-11-03T18:49:06.000Z","location":"https://grantcare.visualstudio.com/_apis/git/repositories/1ab6579f-a5fd-423b-955c-dd56829384bc/commits/6525b4d40403fdf6d278d0a1fc2bedaaca0ebb60","pusher":"c9a11d9c-9cd4-67b9-af06-f1c4378a5d0d","changes":[]},{"id":"cd897d28254be961ec6cbf05c1c52e9c00a473e8","message":"Updated ReleaseNotes-PublishToWiki.yml","type":"TfsGit","author":{"displayName":"Matthew Foos","_links":{"avatar":{"href":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk"}},"id":null,"uniqueName":"matthewf@grantcare.com"},"timestamp":"2020-11-03T18:48:42.000Z","location":"https://grantcare.visualstudio.com/_apis/git/repositories/1ab6579f-a5fd-423b-955c-dd56829384bc/commits/cd897d28254be961ec6cbf05c1c52e9c00a473e8","pusher":"c9a11d9c-9cd4-67b9-af06-f1c4378a5d0d","changes":[]}],"pullRequests":[],"tests":[],"builds":[],"relatedWorkItems":[],"releaseTests":[],"buildDetails":{"_links":{"self":{"href":"https://grantcare.visualstudio.com/e60aae7a-d106-411b-b8f9-6c6de5c66af9/_apis/build/Builds/372"},"web":{"href":"https://grantcare.visualstudio.com/e60aae7a-d106-411b-b8f9-6c6de5c66af9/_build/results?buildId=372"},"sourceVersionDisplayUri":{"href":"https://grantcare.visualstudio.com/e60aae7a-d106-411b-b8f9-6c6de5c66af9/_apis/build/builds/372/sources"},"timeline":{"href":"https://grantcare.visualstudio.com/e60aae7a-d106-411b-b8f9-6c6de5c66af9/_apis/build/builds/372/Timeline"},"badge":{"href":"https://grantcare.visualstudio.com/e60aae7a-d106-411b-b8f9-6c6de5c66af9/_apis/build/status/21"}},"properties":{},"tags":[],"validationResults":[],"plans":[{"planId":"213fda5f-f17d-4d33-a1c3-e455b4e0c2bb"}],"triggerInfo":{},"id":372,"buildNumber":"Solution - QA-20201103..14","status":1,"queueTime":"2020-11-03T18:51:15.763Z","startTime":"2020-11-03T18:51:24.196Z","url":"https://grantcare.visualstudio.com/e60aae7a-d106-411b-b8f9-6c6de5c66af9/_apis/build/Builds/372","definition":{"drafts":[],"id":21,"name":"Solution - QA","url":"https://grantcare.visualstudio.com/e60aae7a-d106-411b-b8f9-6c6de5c66af9/_apis/build/Definitions/21?revision=2","uri":"vstfs:///Build/Definition/21","path":"\\Pearland","type":2,"queueStatus":0,"revision":2,"project":{"id":"e60aae7a-d106-411b-b8f9-6c6de5c66af9","name":"GrantCare","description":"The default project collection for GrantCare. GrantCare Project Collection - GCPC","url":"https://grantcare.visualstudio.com/_apis/projects/e60aae7a-d106-411b-b8f9-6c6de5c66af9","state":"wellFormed","revision":146,"visibility":0,"lastUpdateTime":"2020-11-02T04:03:16.743Z"}},"buildNumberRevision":14,"project":{"id":"e60aae7a-d106-411b-b8f9-6c6de5c66af9","name":"GrantCare","description":"The default project collection for GrantCare. GrantCare Project Collection - GCPC","url":"https://grantcare.visualstudio.com/_apis/projects/e60aae7a-d106-411b-b8f9-6c6de5c66af9","state":"wellFormed","revision":146,"visibility":0,"lastUpdateTime":"2020-11-02T04:03:16.743Z"},"uri":"vstfs:///Build/Build/372","sourceBranch":"refs/heads/master","sourceVersion":"0eba0db14e29904ed23c1a8b580595163cfd5162","priority":3,"reason":1,"requestedFor":{"displayName":"Matthew Foos","url":"https://spsprodcus2.vssps.visualstudio.com/Aa40580e6-8061-4cb8-b4af-93044207950b/_apis/Identities/c9a11d9c-9cd4-67b9-af06-f1c4378a5d0d","_links":{"avatar":{"href":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk"}},"id":"c9a11d9c-9cd4-67b9-af06-f1c4378a5d0d","uniqueName":"matthewf@grantcare.com","imageUrl":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk","descriptor":"aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk"},"requestedBy":{"displayName":"Matthew Foos","url":"https://spsprodcus2.vssps.visualstudio.com/Aa40580e6-8061-4cb8-b4af-93044207950b/_apis/Identities/c9a11d9c-9cd4-67b9-af06-f1c4378a5d0d","_links":{"avatar":{"href":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk"}},"id":"c9a11d9c-9cd4-67b9-af06-f1c4378a5d0d","uniqueName":"matthewf@grantcare.com","imageUrl":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk","descriptor":"aad.YzlhMTFkOWMtOWNkNC03N2I5LWFmMDYtZjFjNDM3OGE1ZDBk"},"lastChangedDate":"2020-11-03T18:51:24.193Z","lastChangedBy":{"displayName":"Microsoft.VisualStudio.Services.TFS","url":"https://spsprodcus2.vssps.visualstudio.com/Aa40580e6-8061-4cb8-b4af-93044207950b/_apis/Identities/00000002-0000-8888-8000-000000000000","_links":{"avatar":{"href":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwNDZkNjI4OA"}},"id":"00000002-0000-8888-8000-000000000000","uniqueName":"00000002-0000-8888-8000-000000000000@2c895908-04e0-4952-89fd-54b0046d6288","imageUrl":"https://grantcare.visualstudio.com/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwNDZkNjI4OA","descriptor":"s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwNDZkNjI4OA"},"orchestrationPlan":{"planId":"213fda5f-f17d-4d33-a1c3-e455b4e0c2bb"},"logs":{"id":0,"type":"Container","url":"https://grantcare.visualstudio.com/e60aae7a-d106-411b-b8f9-6c6de5c66af9/_apis/build/builds/372/logs"},"repository":{"id":"1ab6579f-a5fd-423b-955c-dd56829384bc","type":"TfsGit","name":"pearland-emergency-assistance","url":"https://grantcare.visualstudio.com/GrantCare/_git/pearland-emergency-assistance","clean":null,"checkoutSubmodules":false},"keepForever":false,"retainedByRelease":false,"triggeredByBuild":null},"inDirectlyAssociatedPullRequests":[]}
End of payload data dump
Writing payload data to file /home/vsts/work/1/a/payload.json
Loading template file /home/vsts/work/1/s/ReleaseNotesTemplate.md
Loading handlebars-helpers extension
Completed processing template
Writing output file /home/vsts/work/1/a/releasenotes.md
Finished writing output file /home/vsts/work/1/a/releasenotes.md
Finishing: XplatGenerateReleaseNotes

Again, I'd be willing to pay for an hour session to get this all working properly as it's just taking far too much time to get this up and running.  Keep me posted and thanks again!  😃👍

**Comment by foosfam** [comment]
Follow Up:
      Here are my tasks

      - task: XplatGenerateReleaseNotes@3
        inputs: 
            # Required arguments
            outputfile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'
            templateLocation: File
            templatefile: ReleaseNotesTemplate.md [<-- This file is on the root of my repo]
            dumpPayloadToConsole: true
            dumpPayloadToFile: true
            replaceFile: true
            appendToFile: true
            getParentsAndChildren: false

      - task: WikiFolderUpdaterTask@1
        inputs: 
            # Required arguments
            repo: 'XXXXXXXX.visualstudio.com/XXXXXXXX/_git/XXXXXXXX.wiki'
            targetFolder: 'XXXXXXXX'  [<-- This folder is on root of wiki]
            replaceFile: true
            appendToFile: true
            user: <username>
            password: <token>
            useagenttoken: false
            sourceFolder: ${Build.ArtifactStagingDirectory)
            Filter: '*.md'
            message: 'Update from Build'
            gitname: builduser
            gitemail: 'build@grantcare'
            localpath: $(System.DefaultWorkingDirectory)\repo

**Comment by rfennell** [comment]
Happy to keep answer these support issue

# Can't enrich the commits
This is more of a warning, you have the basic information, but it can't get any extra because as the error say

`Cannot enriched as location URL not in dev.azure.com format`

This is because you are still using the old `xxx.visualstudio.com` organisation name as opposed to the newer `dev.azure.com/xxx` format. The task cannot handle these old URLs for commit enrichment.

Have a look at [this documentation](https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sep-10-azure-devops-launch#administration) on changing URL format.

# Wiki Upload
I do not usually my my `WikiFolderUpdaterTask` for this upload job, but rather  single file  equivalent `WikiUpdaterTask`. e.g.

```
- task: WikiUpdaterTask@1
  inputs:
    repo: 'dev.azure.com/richardfennell/Git-project/_git/Git-project.wiki'
    filename: 'releasenotes.md'
    dataIsFile: true
    sourceFile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'
    message: 'Update from Release - $(Release.ReleaseName) with Creds'
    tagRepo: false
    gitname: builduser
    gitemail: 'build@demo'
    useAgentToken: false
    user: richardfennell
    password: '$(AzureDevOpsPAT)'
    localpath: '$(System.DefaultWorkingDirectory)\repo1'
```

This should address the "can't find the file issue"

**Comment by foosfam** [comment]
**IT WORKS!!!!** 😃👍

You are a legend.  This is fantastic Richard!

**Comment by fromaus-37** [comment]
Thanks a lot Richard, both for the excellent tasks and for your support!

I was facing exactly the same problem and got it to work using OAuth [as you described above](https://github.com/rfennell/AzurePipelines/issues/845#issuecomment-721007356) but with a few differences. I thought I'd share my settings as some of the options are different now (over two years later):

* At All Repositories level (**Project Settings | Repos | Repositories** page, then **Security** tab instead of selecting a repository on the **Repository** tab of the page) I **didn't assign Contribute permission** to either the project's Build Service account or the Project Collection Build Service Account.
* But I did [set Wiki permissions](https://learn.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops) so that both the projects Build Service account and the Project Collection Build Service group had **Contribute** permission (i.e. the Commit permission that you mentioned).
* On top of the above, to get the task working  I had to **switch off** the option **Protect access to repsositories in YAML pipelines** on **Project Settings | Pipelines | Settings** page. This is similar to the option you described but the wording has probably changed.
    
    ![image](https://user-images.githubusercontent.com/20386346/217157741-f1ce3eae-7ecb-45a4-b03e-e088f43a6e13.png)

    However I then switched it back on (it's probabaly securer that way) and instead defined the wiki repo as a resource (but didn't check it out using `checkout` task) in the pipeline that contains the `WikiUpdaterTask@2`. This did the trick:

    ```
    resources:
      repositories:
        - repository: WikiRepo #this can be any name you like, just a local name for repo
          type: git
          name: <Project name>/<Project Name>.wiki

    trigger:
      - main
    pool:
      vmImage: ubuntu-22.04
   
    ```

**Comment by rfennell** [comment]
Thanks @foosfam, looks like the UX has changed yet again and a readme/wiki update is required with your text as the basic

**Comment by fromaus-37** [comment]
I am using your task exactly as normal, only declaring the repository resource so that the scope of the job access token (presumably this token is for the account under which the pipeline is run, which in my case is most probabaly the project's Build Service account as I haven't changed the defaults) includes the wiki repo as well. 

I was pointed in this direction by text in the **Protect access to repositories in the YAML pipelines** which says:

> ...generate a job access token that is scoped to repositories that are explicitly referenced in the YAML pipeline

I thought if I tried to `checkout: <wiki repo URL>`, it would mess with the paths in other tasks in my pipeline. 

If there's just one `checkout: `, which there is by default as repo that contains the pipeline is checked out implicitly, then the repo is downloaded to `s` folder and I think all the tasks assume the path is `/s`. But if there are multiple `checkout` commands, e.g. a second `checkout: <wiki repo URL>`, then I think I would have needed to adjust paths in my other tasks.

Therefore I only refernced the wiki repo at the top of the pipeline without a `checkout: WikiRepo` further down in the pipeline.
