### ISSUE TITLE
Missing template file 

### ISSUE THREAD

**Issue by skandula106** [rfennell/AzurePipelines#882]
I am getting this error while my pipe line was running can any pls help i am facing this issue from past a week 

The template is not on handlebars format, load template has been skipped
Missing template file
Missing template file

![Capture](https://user-images.githubusercontent.com/58414973/98936264-bb777180-250a-11eb-8955-0bcb155bee56.PNG)

**Comment by rfennell** [comment]
V3 of the Cross Platform Release Note task only supports Handlebar format templates.

If you wish to use the legacy format you must select V2 of this task (using the task version drop down) which supports both legacy and handlebar formats

The move to supporting only Handlebars in V3 is because it make the task much more flexible and easy to enhance. Dropping legacy format templates allows V3 to have many more features than V3

You can find the documentation for the Handlebars usage [here](https://github.com/rfennell/AzurePipelines/wiki/GenerateReleaseNotes---Node-based-Cross-Platform-Task) and extra sample templates [here](https://github.com/rfennell/AzurePipelines/tree/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203). The migration is not that complex

**Comment by skandula106** [comment]
Thank you for the reply i am facing some other issue also for now previous
issue was fixed
