### ISSUE TITLE
Is it working also for TFS or only git 

### ISSUE THREAD

**Issue by Shlomtzi** [rfennell/AzurePipelines#968]
I run the template and its works  but not get any coomits 
I working on TFS and not  Git , is it work?

**Comment by rfennell** [comment]
The API calls used to find the associated Commits or ChangeSets are actually the same so, yes Git and TFVC are both supported options. 

Though it is fair to say there has been much more testing of the Git usage due to the fact most development teams seem to have moved in that direction.

Remember that only changeset sets associated since the last successful build will be found.

You can see the calls being made if you run the build with a variable `system.debug=true` set.
